project_name: traefik-plugin-geoblock

builds:
  # traefik plugins are not built in advance, but interpreted by
  # yaegi. Building plugins doesn't make sense, but we want to use
  # the other goodies of GoReleaser.
  - skip: true

release:
  prerelease: auto

source:
  enabled: true

sboms:
  - artifacts: source
    documents:
      - "${artifact}.cdx.sbom"
    cmd: cyclonedx-gomod
    args: ["mod", "-licenses", "-json", "-output", "$document", "./.."]

milestones:
  - name_template: "{{ .Tag }}"
    close: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge '