displayName: geoblock
type: middleware
import: github.com/nscuro/traefik-plugin-geoblock
summary: Description of what my plugin is doing
testData:
  enabled: true
  databaseFilePath: IP2LOCATION-LITE-DB1.IPV6.BIN
  allowedCountries: [ "CH", "DE" ]
  allowPrivate: true