apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  name: traefik
  namespace: traefik
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: traefik
    spec:
      initContainers:
      - name: geoblock-install
        image: ghcr.io/ulexus/traefik-plugin-geoblock:latest
        volumeMounts:
        - name: plugins
          mountPath: /plugins-local
      containers:
      - args:
        - --entrypoints.metrics.address=:9100/tcp
        - --entrypoints.traefik.address=:9000/tcp
        - --entrypoints.web.address=:8000/tcp
        - --entrypoints.websecure.address=:8443/tcp
        - --entrypoints.websecure.http.tls=true
        - --experimental.localplugins.geoblock.modulename=github.com/nscuro/traefik-plugin-geoblock
        - --api.dashboard=true
        - --ping=true
        - --metrics.prometheus=true
        - --metrics.prometheus.entrypoint=metrics
        - --tracing=$(TRACING)
        - --tracing.jaeger=true
        - --tracing.jaeger.propagation=b3
        - --providers.kubernetescrd
        - --providers.kubernetescrd.allowCrossNamespace=true
        - --providers.kubernetesingress
        - --providers.kubernetesingress.ingressendpoint.publishedservice=$(POD_NAMESPACE)/traefik
        - --entrypoints.web.http.middlewares=$(DEFAULT_MIDDLEWARES)
        - --entrypoints.websecure.http.middlewares=$(DEFAULT_MIDDLEWARES)
        - --entryPoints.web.proxyProtocol.trustedIPs=$(PROXY_PROTOCOL_TRUSTED_IPS)
        - --entryPoints.websecure.proxyProtocol.trustedIPs=$(PROXY_PROTOCOL_TRUSTED_IPS)
        env:
        - name: JAEGER_ENDPOINT
          value: http://grafana-agent-traces.grafana-agent-operator.svc:14268/api/traces
        - name: TRACING
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DEFAULT_MIDDLEWARES
          value: $(POD_NAMESPACE)-report-uri@kubernetescrd
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: PROXY_PROTOCOL_TRUSTED_IPS
          value: 10.225.0.0/18
        image: traefik:v2.10.4@sha256:429f3398a3cd1aa7436aa4f59d809040d3903506a9d83bee61688bb1429c7693
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: traefik
        ports:
        - containerPort: 9100
          name: metrics
          protocol: TCP
        - containerPort: 9000
          name: traefik
          protocol: TCP
        - containerPort: 8000
          name: web
          protocol: TCP
        - containerPort: 8443
          name: websecure
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /plugins-local
          name: plugins
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65532
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: traefik
        matchLabelKeys:
        - pod-template-hash
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: traefik
        matchLabelKeys:
        - pod-template-hash
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - emptyDir: {}
        name: plugins
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: tmp
