name: GoReleaser

on:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  Release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout Repository
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
      with:
        go-version: "1.19"
    - name: Install cyclonedx-gomod
      uses: CycloneDX/gh-gomod-generate-sbom@d4aee0cf5133055dbd98899978246c10c18c440f # tag=v1
      with:
        version: v1
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@8f67e590f2d095516493f017008adc464e63adb1 # v4
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}